
server:
  port: 8585

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mentoria
    username: root
    password: root
  driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
